test("Hello World",()=>{

});

test("Error",()=>{
    throw new Error("the test is getting failed ")
})